target 'TWGExtensions', :exclusive => true do
  pod "TWGExtensions", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TWGExtensions", :path => "../"

  pod 'Expecta'
  pod 'OCMock'
  pod 'FBSnapshotTestCase'
end
